sudo: required
services:
  - docker
before_install:
  - docker build -t zafergenc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zafergenc/react-test npm test

after_success:
  - docker build -t zafergenc/multi-client ./client
  - docker build -t zafergenc/multi-nginx ./nginx
  - docker build -t zafergenc/multi-server ./server
  - docker build -t zafergenc/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zafergenc/multi-client
  - docker push zafergenc/multi-nginx
  - docker push zafergenc/multi-server
  - docker push zafergenc/multi-worker

